<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by Maarten van den Broek (messageDesign) -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:imgeo="http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3" xmlns:StUF="http://www.egem.nl/StUF/StUF0301" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3">
	<import namespace="http://www.egem.nl/StUF/StUF0301" location="../../0301/stuf0301_types.wsdl"/>
	<documentation>
		Dit document definieert de webservices voor het portType OntvangAsynchroon voor de berichtencatalogus horizontaal en voor een bor-applicatie
		Version: 030200
		
		Wijzigingen vergeleken met versie 030100:
			- imgeo:namespace en target namespace gewijzigd in http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3
			- in import element binnen het schema element de namespace gewijzigd in "http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3"en de schemaLocation in "imgeo0302_msg_horizontaal.xsd"
			- binnen het attribute soapAction overal "http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.2" vervangen door "http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3"
	</documentation>
	<types>
		<xs:schema>
			<xs:import namespace="http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3" schemaLocation="imgeo0302_msg_horizontaal.xsd"/>
		</xs:schema>
	</types>
	<message name="expDu01">
		<part name="body" element="imgeo:expDu01"/>
	</message>
	<message name="mtbHorizontaalDi01">
		<part name="body" element="imgeo:mtbHorizontaalDi01"/>
	</message>
	<message name="mtvWeigerDu01">
		<part name="body" element="imgeo:mtvWeigerDu01"/>
	</message>
	<portType name="OntvangAsynchroon">
		<documentation>
		Dit portType ondersteunt als operaties alle asynchrone berichten gedefinieerd binnen het sectormodel

		Hieronder is steeds als output message StUF:Bv03 gedefinieerd. Dit is correct voor een StUF-endnode. Voor intermediaire nodes die de StUF-fouthandeling op het niveau van de StUF:stuurgegevens niet implementeren dienen in plaats van een StUF:Bv03 een StUF:Bv04 als respons te sturen (<output message="StUF:Bv04"/>). Dergelijke systemen dienen zelf hun wsdl hierop aan te passen (ook binnen het binding element moeten dan aanpassingen worden doorgevoerd).
	</documentation>
		<operation name="expDu01">
			<input message="imgeo:expDu01"/>
			<output message="StUF:Bv03"/>
			<fault name="fout" message="StUF:Fo03"/>
		</operation>
		<operation name="mtbHorizontaalDi01">
			<input message="imgeo:mtbHorizontaalDi01"/>
			<output message="StUF:Bv03"/>
			<fault name="fout" message="StUF:Fo03"/>
		</operation>
		<operation name="mtvWeigerDu01">
			<input message="imgeo:mtvWeigerDu01"/>
			<output message="StUF:Bv03"/>
			<fault name="fout" message="StUF:Fo03"/>
		</operation>
		<operation name="Fo03">
			<input message="StUF:Fo03"/>
			<output message="StUF:Bv03"/>
			<fault name="fout" message="StUF:Fo03"/>
		</operation>
	</portType>
	<binding name="SOAPOntvangAsynchroon" type="imgeo:OntvangAsynchroon">
		<documentation>
			Omdat de uit te wisselen berichten volledig gedefinieerd zijn in het sectormodel cq de StUF-standaard, kunnen we ze zonder verdere encoding (“literal”) opnemen in de body.
Niet ondersteunde berichten kunnen uit de binding en portType worden verwijderd.
		</documentation>
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="expDu01">
			<soap:operation soapAction="http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3/expDu01"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="fout">
				<soap:fault name="fout" use="literal"/>
			</fault>
		</operation>
		<operation name="mtbHorizontaalDi01">
			<soap:operation soapAction="http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3/mtbHorizontaalDi01"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="fout">
				<soap:fault name="fout" use="literal"/>
			</fault>
		</operation>
		<operation name="mtvWeigerDu01">
			<soap:operation soapAction="http://www.geostandaarden.nl/imgeo/2.1/stuf-imgeo/1.3/mtvWeigerDu01"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="fout">
				<soap:fault name="fout" use="literal"/>
			</fault>
		</operation>
		<operation name="Fo03">
			<soap:operation soapAction="http://www.egem.nl/StUF/StUF0301/Fo03"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="fout">
				<soap:fault name="fout" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="OntvangAsynchroon">
		<documentation>
	Hieronder wordt de concreet aan te roepen service voor het ontvangen van asynchrone IMGeo2.0 kennisgevingberichten gedefinieerd door een bor-applicatie. 
		</documentation>
		<port name="OntvangAsynchroon" binding="imgeo:SOAPOntvangAsynchroon">
			<documentation>
				<wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.1"/>
			</documentation>
			<soap:address location="http://example.com/OntvangAsynchroon"/>
		</port>
	</service>
</definitions>
